/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package smartGrader.GUI;

//import java.awt.BorderLayout;
//import java.awt.Dimension;
import java.awt.BasicStroke;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.util.logging.Level;
import java.util.logging.Logger;
//import javax.swing.BorderFactory;
//import javax.swing.ImageIcon;
//import javax.swing.JComboBox;
import javax.swing.JPanel;
import javax.swing.JTextPane;
import javax.swing.text.BadLocationException;
import javax.swing.text.StyledDocument;
import static smartGrader.GUI.eGrader_Worker.CurrentScore;
import smartGrader.scriptGrading.MarkScript;

/**
 *
 * @author LabaPc
 */
public class Marker2 extends javax.swing.JDialog {

    /**
     * Creates new form feedBackDisplay
     */
    Graphics g;
    int x, y = 0;
    boolean canMark = false;
    JTextPane jTextPaneGrader;

    public Marker2(java.awt.Frame parent, boolean modal, int x, int y, Graphics g, boolean canMark, JTextPane grader) {
        super(parent, modal);
        initComponents();
        this.x = x;
        this.y = y;
        this.g = g;
        g = grader.getGraphics();
        this.jTextPaneGrader = grader;
        this.canMark = canMark;
        if (canMark == true) {
            jButtonAssignMark.setEnabled(true);
            jButtonAppendText.setEnabled(true);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreafeed = new javax.swing.JTextArea();
        jButtonAppendText = new javax.swing.JButton();
        jButtonAssignMark = new javax.swing.JButton();
        jSpinnerSetMark = new javax.swing.JSpinner();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(400, 150));
        setMinimumSize(new java.awt.Dimension(400, 150));
        setPreferredSize(new java.awt.Dimension(190, 220));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jTextAreafeed.setColumns(20);
        jTextAreafeed.setRows(5);
        jScrollPane1.setViewportView(jTextAreafeed);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 230, 60));

        jButtonAppendText.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jButtonAppendText.setForeground(new java.awt.Color(0, 102, 204));
        jButtonAppendText.setText("Append Text");
        jButtonAppendText.setEnabled(false);
        jButtonAppendText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAppendTextActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAppendText, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, -1, 30));

        jButtonAssignMark.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jButtonAssignMark.setForeground(new java.awt.Color(0, 102, 204));
        jButtonAssignMark.setText("OK");
        jButtonAssignMark.setEnabled(false);
        jButtonAssignMark.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAssignMarkActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAssignMark, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, -1, -1));

        jSpinnerSetMark.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jSpinnerSetMark.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, 100.0d, 0.5d));
        getContentPane().add(jSpinnerSetMark, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 90, 40));

        jLabel9.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 102, 204));
        jLabel9.setText("Award Mark");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAppendTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAppendTextActionPerformed
        MarkScript ms = new MarkScript();
        String text = jTextAreafeed.getText();
        ms.paint(g, text, x, y);

        jTextPaneGrader.updateUI();
        this.dispose();

    }//GEN-LAST:event_jButtonAppendTextActionPerformed


    private void jButtonAssignMarkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAssignMarkActionPerformed

        String Score = null;
        // jSpinnerSetMark.getValue();
        MarkScript ms = new MarkScript();
        Score = ms.getSpinnerValue(jSpinnerSetMark).toString();

        ms.paint(g, Score, x, y);
        jTextPaneGrader.revalidate();
        CurrentScore.add(Double.parseDouble(Score));
        this.dispose();

    }//GEN-LAST:event_jButtonAssignMarkActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Marker2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Marker2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Marker2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Marker2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                Marker2 dialog = new Marker2(new javax.swing.JFrame(), true, x, y, g, canMark);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAppendText;
    private javax.swing.JButton jButtonAssignMark;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinnerSetMark;
    private javax.swing.JTextArea jTextAreafeed;
    // End of variables declaration//GEN-END:variables
}
